### PR TITLE
Tyler Brassel added Github username

### PR DESCRIPTION
**Pull request by tbrassel**

### CODE REVIEW

**Comment by jnmaloof** [comment]
What editor did you use?  Github shows every line changed.  Perhaps this is due to your editor changing line endings?  Not an issue with other students.

**Comment by tbrassel** [comment]
I used Rstudio. I didn’t use any gui controls and used the command line
after adding my username. Do you need me to resubmit it? I will look into
my line ending preferences.

**Comment by jnmaloof** [comment]
Of course I can add your username myself, since it is in the pull request, but if you have time take a look and see if you can figure out what happened.

**Comment by jnmaloof** [comment]
I am adding you manually.

**Pull request closed without merging**
