### PR TITLE
add an auditor Yige Luo

### PR DESCRIPTION
**Pull request by drosophila92**

### CODE REVIEW

**Comment by jnmaloof** [comment]
got it.  If you are auditing you should email me so that I can add you to Canvas

**Comment by drosophila92** [comment]
Hi Julin,

Thanks for reaching me. Yes, I would like to be added in Canvas.  Please let me know if there is anything needed from me.

Sincerely,
Yige 

Yige LUO

Kopp Lab PhD student

Population Biology Graduate Group

University of California - Davis ‪

One Shields Ave‬ ‪, Davis, CA, 95616‬

**Comment by jnmaloof** [comment]
I need your UCD email to add you to Canvas

Also you need to add your github user name, not just your name, to the gh-usernames file.

**Comment by drosophila92** [comment]
My UCD email is:
ygeluo@ucdavis.edu

My GitHub username is:
drosophila92

Sincerely,
Yige 
Yige LUO

Kopp Lab PhD student

Population Biology Graduate Group

University of California - Davis ‪

One Shields Ave‬ ‪, Davis, CA, 95616‬

**Pull request merged**
